### ISSUE TITLE
Loop detection in linked list using Floyd cycle detection method in c++

### ISSUE THREAD

**Issue by Prakersh123** [Algo-Phantoms/Algo-Tree#1297] opened 2021-03-24 12:57 UTC
**Is your feature request related to a problem? Please describe.**
Sir/Ma'am, I want to implement the code of loop detection in a linked list using Floyd cycle detection method.

Please assign this task to me :)
Thank-you.
@rudrakshi99@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99

**Comment by rudrakshi99** [comment] 2021-03-25 17:53
@Prakersh123 Don't make PR until the issue is not assigned to you.

**Comment by tarun26091999** [comment] 2021-03-28 14:05
present at #189

**Closed by tarun26091999** 2021-03-28 14:05 UTC
Labels: duplicate
