### ISSUE TITLE
Reverse Level Order Traversal

### ISSUE THREAD

**Issue by kirtijha014** [Algo-Phantoms/Algo-Tree#1248] opened 2021-03-22 05:16 UTC
In this issue, 
**Problem Statement:** Given a binary tree of size N, we will find its reverse level order traversal.

**Input:**
      10 
       /\
  20   30
 /  \ 
40  60

**Output:** 40 60 20 30 10

**Explanation:**
Traversing level 2:  40 60
Traversing level 1:  20 30
Traversing level 0:  10

**Languages:** C++,Java

Please assign me with this issue:
@plazzy99 @rudrakshi99 @nakul-19 @tarun26091999 @OjusWiZard @shreyanspoddar @raksha009 @anjul2000

**Comment by hritikkhurana10sm** [comment] 2021-03-22 05:43
Hey , this side is Hritik Khurana , GSSOC'21 Participant , looking for 1st pr , please assign this issue to u . I will write code in C++,
Please assign me :
@plazzy99 @rudrakshi99 @nakul-19 @tarun26091999 @OjusWiZard @shreyanspoddar @raksha009 @anjul2000

**Comment by Aarti002** [comment] 2021-03-23 18:57
hey @tarun26091999 can i work on this issue in python?
Thank you!

**Comment by rudrakshi99** [comment] 2021-03-25 17:34
The issue is not assigned to you.

**Closed by rudrakshi99** 2021-03-25 17:34 UTC
