### ISSUE TITLE
Bitwise Operation

### ISSUE THREAD

**Issue by amankhanathani** [Algo-Phantoms/Algo-Tree#1721] opened 2021-04-24 17:55 UTC
**Is your feature request related to a problem? Please describe.**
Count the number of set bits in an integer

**Describe the solution you'd like**
Will use bit manipulation to return the number of 1s in the integer's binary format

**Do you want to work on it**
I will use C++.

**Comment by Srishti013** [comment] 2021-04-25 03:44
Hi,
I am a GSSOC'21  participant, I would like to solve this in C++. Please  assign this issue to me.

**Comment by shubhidua** [comment] 2021-04-26 16:53
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.

**Comment by OjusWiZard** [comment] 2021-04-27 14:55
Duplicate of #44

**Closed by OjusWiZard** 2021-04-27 14:55 UTC
Labels: duplicate
