### ISSUE TITLE
Sorting the elements in increasing/Decreasing order by QuickSort

### ISSUE THREAD

**Issue by SanketH17** [Algo-Phantoms/Algo-Tree#1271] opened 2021-03-22 18:48 UTC
Given the array :
a = [9,5,3,4,8,7,5,1,4,,9,8,6,7]
to sort these elements (in increasing order) ;
We can input the elements from the user as well but I am making it for the already made array.

Hey @chitrasingla I want to add this into Algo-Tree/code/c++
Please check it out

**Comment by rudrakshi99** [comment] 2021-03-25 17:47
@sakshi2707 Do not make PR until the issue is not assigned to you.

**Closed by rudrakshi99** 2021-03-25 17:47 UTC
