### ISSUE TITLE
Staircase Search

### ISSUE THREAD

**Issue by ritikpanchal768** [Algo-Phantoms/Algo-Tree#558] opened 2021-03-11 06:16 UTC
Problem:- we have a 2-d array having its rows and columns sorted .you want to search a given element in it with a time complexity of O(n).

I want to work on this problem. Kindly assign it to me.

**Comment by sumitsantape30** [comment] 2021-03-11 06:56
I would like to resolve this issue, will be implementing using Java, Please assign me this.
I'm GSSoC21 participant.

**Comment by OjusWiZard** [comment] 2021-04-02 20:07
Duplicate of #385

**Closed by OjusWiZard** 2021-04-02 20:07 UTC
