### ISSUE TITLE
Java program for Perfect number

### ISSUE THREAD

**Issue by IdealisticINTJ** [Algo-Phantoms/Algo-Tree#843] opened 2021-03-13 09:46 UTC

**Comment by Simar05519** [comment] 2021-03-13 14:54
I want to work on this issue. Please assign to me.

**Comment by krishna-NIT** [comment] 2021-03-13 17:16
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by OjusWiZard** [comment] 2021-04-04 13:41
Duplicate of #753

**Closed by OjusWiZard** 2021-04-04 13:41 UTC
