### ISSUE TITLE
Large Factorial

### ISSUE THREAD

**Issue by AdityaRaj-ar** [Algo-Phantoms/Algo-Tree#1754] opened 2021-04-27 02:10 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
-Finding the very Big Factorial

**Describe the solution you'd like**
-Solution must carry necessary comment lines explaining the steps. 

**Do you want to work on it**
Mention the one language you want to be assigned for this issue.
I want to work on this issue in JAVA language.

**Comment by Mugdha-Hazra** [comment] 2021-04-27 06:01
Hello @aaadddiii @anubhavitis @veenit1802 @ssaksham @malavikarajeshvikraman, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by vanshikachokhani** [comment] 2021-04-27 08:19
I would like to work on this issue in C++

**Comment by OjusWiZard** [comment] 2021-04-27 14:19
Duplicate of #362

**Closed by OjusWiZard** 2021-04-27 14:19 UTC
