### ISSUE TITLE
Full linked list implementation using class having function insert node , delete node , size of linked etc 

### ISSUE THREAD

**Issue by anshulsharma123** [Algo-Phantoms/Algo-Tree#813] opened 2021-03-12 21:08 UTC
Hello admins please assign this issue to me I would like to add linked list code in c++ language

**Comment by japneetbhatia** [comment] 2021-03-12 22:07
Hello, please assign this issue to me in Java. I will implement all Linked List function in class
[gssoc'21]

**Comment by Aarti002** [comment] 2021-03-12 23:36
hey @tarun26091999 can i do this issue in python, under gssoc'21.
Thank you!

**Comment by 04akvs** [comment] 2021-03-13 06:51
Hello, may I  work on this issue?

**Comment by nishantsahu961** [comment] 2021-03-13 08:00
I would like to work upon this issue in java/c++  with test cases , @tarun26091999  please assign this to me

**Comment by Rajashri14** [comment] 2021-03-15 12:18
Hello , I would like to work upon this issue in java. Please assign this issue to me.

**Comment by OjusWiZard** [comment] 2021-04-04 10:46
Duplicate of https://github.com/Algo-Phantoms/Algo-Tree/blob/68f1222e687425500cfabe01e2d442aac3ca7aea/Linked_list/readme.md
#513 #805

**Closed by OjusWiZard** 2021-04-04 10:46 UTC
