### ISSUE TITLE
Brian Kernighan's Algorithm (Count no of Set Bits)

### ISSUE THREAD

**Issue by debanjan-2002** [Algo-Phantoms/Algo-Tree#44] opened 2021-02-18 17:27 UTC
Sir,
I have made an extensive C++ file for Brian Kernighan's algorithm. I have explained the intuition and idea of the algorithm briefly.
I have made a pull request regarding the same. Please review my request and if you feel that it is worth it, then please merge it.
Link to PR- https://github.com/Algo-Phantoms/Algo-Tree/pull/43
@plazzy99
@rudrakshi99
@nakul-19

I have been selected for GSSOC'21, and I am really interested in DSA, so I would like to contribute in this amazing repository.
Regards,
Debanjan Poddar

**Comment by debanjan-2002** [comment] 2021-02-19 13:31
Sir,
I have added SIEVE OF ERATOSTHENES code in C++. I have written it briefly, explaining each and every step and also added some test cases. It would be really nice of you if you review my pull request. Also, previously I had added BRIAN KERNIGHAN'S algorithm, which is yet to be reviewed by you. It would be really nice of you if you check my PR and if you think it is worth it, then consider merging it.
@plazzy99
@rudrakshi99
@nakul-19

Link to Pull Request (PR) - #43  

Regards,
Debanjan Poddar

**Comment by 1vivekanand** [comment] 2021-03-05 14:16
Hello @rudrakshi99 @nakul-19 @plazzy99 
I am a GSSOC'21 participant
I would like to contribute in this issue : Brian Kernighan's Algorithm
My language of code will be java with proper comment for better understanding.
I will add 2-3 testcases.
I will explain the time and space complexity of my approach

**Comment by plazzy99** [comment] 2021-03-06 09:52
> Sir,
> I have added SIEVE OF ERATOSTHENES code in C++. I have written it briefly, explaining each and every step and also added some test cases. It would be really nice of you if you review my pull request. Also, previously I had added BRIAN KERNIGHAN'S algorithm, which is yet to be reviewed by you. It would be really nice of you if you check my PR and if you think it is worth it, then consider merging it.
> @plazzy99
> @rudrakshi99
> @nakul-19
> 
> Link to Pull Request (PR) - #43
> 
> Regards,
> Debanjan Poddar

Link your pull request to this issue by using #<issue_no.>

**Comment by debanjan-2002** [comment] 2021-03-06 10:12
SIR,
I HAVE LINKED THE PR.
Please review it. I have written a brief code.
Regards,
Debanjan Poddar

**Comment by debanjan-2002** [comment] 2021-03-08 16:24
Sir I have made the changes as stated by you and have made a new pull request.
Link to PR #208
It fixes this issue.
Fixes - #43 
Regards,
Debanjan Poddar

**Comment by 1vivekanand** [comment] 2021-03-08 17:26
Sir, I have Made the PR #218 
it fixes the issue #44
Regards.
Vivekanand Bhardwaj

**Comment by ganesh-sai-a** [comment] 2021-03-20 04:36
Hey! @plazzy99 @rudrakshi99 @nakul-19 
I am GSSOC21 participant. I would like to contribute to this issues. 
I will implement Brian Kernighan's Algo in C++ with adding proper comments.
Can you please assign me this issue.

**Comment by shahina-bano** [comment] 2021-03-20 08:01
I will solve this problem using python, please assign me.

**Comment by 1vivekanand** [comment] 2021-03-21 17:32
Sir, I have made the PR #1243 
it fixes the issue #441 
Regards
Vivekanand Bhardwaj

**Comment by nikhv** [comment] 2021-04-02 08:34
@tarun26091999  ,please assign this issue to me , I will implement it in c++

**Comment by nikhv** [comment] 2021-04-04 15:22
@raksha009 ,please assign this issue to me .I will implement it in c++.

**Comment by raksha009** [comment] 2021-04-04 15:38
> @raksha009 ,please assign this issue to me .I will implement it in c++.

The issue is already assigned in cpp. Plz look for other issues :)

**Closed** 2021-04-27 14:41 UTC
Labels: Level1, bitmasking, cpp, gssoc21, java, python
