### ISSUE TITLE
Count Sort

### ISSUE THREAD

**Issue by aanchalsethi** [Algo-Phantoms/Algo-Tree#790] opened 2021-03-12 16:11 UTC
I can write the algorithm for the count sort in CPP.

**Comment by abhay27chauhan** [comment] 2021-03-12 17:45
I can write the algorithm for the count sort in Java

**Comment by priyanka001tech** [comment] 2021-03-13 14:41
I can write the algorithm for the count sort in CPP. Please assign this to me.

**Comment by OjusWiZard** [comment] 2021-04-04 08:07
Duplicate of #398 and C++ code already exist in the repository.

**Closed by OjusWiZard** 2021-04-04 08:07 UTC
