### ISSUE TITLE
Implement Queue Data Structure Using Stack

### ISSUE THREAD

**Issue by nishantsahu961** [Algo-Phantoms/Algo-Tree#744] opened 2021-03-12 09:32 UTC

**Comment by D-Ajay-Kumar** [comment] 2021-03-12 09:44
I can do it

**Comment by vedant-jain03** [comment] 2021-03-12 10:10
I can do this issue in cpp and python

**Comment by OjusWiZard** [comment] 2021-04-04 07:37
Duplicate of #514

**Closed by OjusWiZard** 2021-04-04 07:37 UTC
