### ISSUE TITLE
(GSSOC'21)Remove nth node from the end of a link list

### ISSUE THREAD

**Issue by SamarpanCoder2002** [Algo-Phantoms/Algo-Tree#378] opened 2021-03-09 19:31 UTC
I would like to add this(Remove nth node from the end of a link list by C++) in that repo...... **_I am also a gssoc'21 participant_**... If I can forward with that, Please assign me in that...Thank you

**Comment by Vansh-Gupta4** [comment] 2021-03-09 20:50
I would like to add this(Remove nth node from the end of a link list) in that repo...... I am also a gssoc'21 participant.... If I can forward with that, Please assign me in that....I would code in java

**Comment by OjusWiZard** [comment] 2021-04-02 16:14
#201

**Comment by OjusWiZard** [comment] 2021-04-02 16:15
Duplicate of #201

**Closed by OjusWiZard** 2021-04-02 16:15 UTC
Labels: duplicate
