### ISSUE TITLE
Wiggle Sort

### ISSUE THREAD

**Issue by devanshi-code** [Algo-Phantoms/Algo-Tree#734] opened 2021-03-12 07:48 UTC
Hey , I am Devanshi Mishra a GSSOC participant , I want to add an important question which goes like:
Given an unsorted array nums, reorder it in-place such that nums[0] <= nums[1] >= nums[2] <= nums[3]....

For example, given nums = [3, 5, 2, 1, 6, 4], one possible answer is [1, 6, 2, 5, 3, 4].
And add the solution for it too.
Kindly assign me this issue.
Thank you
@anubhavitis @dheerajkotwani @tarun26091999 @avijit1999 @todi-2000

**Comment by Simar05519** [comment] 2021-03-14 08:45
I want to work on this issue. Please assign to me

**Comment by OjusWiZard** [comment] 2021-04-04 07:30
Duplicate of #180

**Closed by OjusWiZard** 2021-04-04 07:30 UTC
