### ISSUE TITLE
Kth smallest element 

### ISSUE THREAD

**Issue by sonal251001** [Algo-Phantoms/Algo-Tree#629] opened 2021-03-11 14:21 UTC
Hello. I want to add this Kth smallest element code in Java. I would push my code into arrays folder . I have read the guidelines and therefore request you to assign it to me. I am a GSSoC'21 Participant.

**Comment by Aarti002** [comment] 2021-03-11 14:53
hey @tarun26091999 @rudrakshi99 under gssoc'21 can i work on this issue in python will provide explanatory comments too.
Thank you!

**Comment by pallavidhere23** [comment] 2021-03-11 15:10
I can implement this issue in java,c++,python.I am good at data structures and algorithm .Please assign me this issue under GSSOC'2021.

**Comment by SwarnimaShishodia** [comment] 2021-03-11 15:21
Hey I can solve this problem using C++

**Comment by kanchan1910** [comment] 2021-03-11 17:45
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by OjusWiZard** [comment] 2021-04-03 19:30
Duplicate of #162

**Closed by OjusWiZard** 2021-04-03 19:30 UTC
Labels: duplicate
