### ISSUE TITLE
Lee's Algorithm

### ISSUE THREAD

**Issue by U-c0de** [Algo-Phantoms/Algo-Tree#1734] opened 2021-04-25 13:27 UTC
**Describe the solution you'd like**
I propose to add Lee Algorithm which is use to find the shortest path in a maze.
Real Life Applications:
Maze Game
Solving Rubik's Cube faster
Map Technology
Social Network

**Do you want to work on it**
I want to add the code in C++

**Comment by U-c0de** [comment] 2021-04-25 13:28
Please assign it to me . @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal

**Comment by Mugdha-Hazra** [comment] 2021-04-25 15:27
Hello, @aaadddiii @anubhavitis @veenit1802 @ssaksham sir, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by shubhidua** [comment] 2021-04-26 16:53
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.

**Comment by OjusWiZard** [comment] 2021-04-27 14:46
Duplicate of #1455

**Closed by OjusWiZard** 2021-04-27 14:46 UTC
