### ISSUE TITLE
Coin Change problem

### ISSUE THREAD

**Issue by guptaa98** [Algo-Phantoms/Algo-Tree#806] opened 2021-03-12 19:00 UTC
Hi 
I would like to work on Coin change problem where we are given coins of different denominations and a total amount of money as amount. 
We need to write the function to compute the fewest number of coins that we'll need to make up that amount. If that amount of money cannot be made up by any combination of the coins, we'll return -1.

for example 
coins = [1,2,5] 
amount = 11
the output will be 3. (5+5+1)

I would write a code in C++.
(Gssoc'21 Participant)

Hey @tarun26091999 kindly assign me this issue.

**Comment by Aarti002** [comment] 2021-03-12 23:40
hello @tarun26091999 under gssoc'21 can i work on this issue in python.
Thank you!

**Comment by Riya1718** [comment] 2021-03-13 12:02
Hey , I am Riya Jain , a GSSOC'21 Participant. I would like to solve this issue using Java.
Thank you!
@tarun26091999

**Comment by OjusWiZard** [comment] 2021-04-04 08:52
Duplicate of #314

**Closed by OjusWiZard** 2021-04-04 08:52 UTC
