### ISSUE TITLE
Huffman encoding and decoding Algorithm

### ISSUE THREAD

**Issue by Ashee-Kanungo** [Algo-Phantoms/Algo-Tree#677] opened 2021-03-11 18:40 UTC
Hey!! @plazzy99 @rudrakshi99 @nakul-19 @tarun26091999 @raksha009 @shreyanspoddar
This is an algorithm which is used for data compression and it gives a basic idea behind file compression.

I would like to implement this using c++.
I assure you that I will write a clear code and properly mention comments in code.
I request you to please assign me this problem.

**Comment by Suvraneel** [comment] 2021-03-11 18:48
Duplicate of  issues #272  & #590

**Closed** 2021-03-11 23:53 UTC
Labels: duplicate
