### ISSUE TITLE
Circular Linked List

### ISSUE THREAD

**Issue by AbhignaSowgandhika02** [Algo-Phantoms/Algo-Tree#360] opened 2021-03-09 16:46 UTC
Hello, I am GSSOC'21 participant and would like to add clean code for linked lists in python.

**Comment by Disha-swp** [comment] 2021-03-11 07:20
Hello, I'm a gssoc participant please assign this to me.

**Comment by OjusWiZard** [comment] 2021-04-02 14:39
Duplicate of #80

**Closed by OjusWiZard** 2021-04-02 14:39 UTC
Labels: duplicate
