### ISSUE TITLE
Implement Stack Class in Python 

### ISSUE THREAD

**Issue by sujoy-coder** [Algo-Phantoms/Algo-Tree#809] opened 2021-03-12 19:37 UTC
Hello, I'm a GSSoC '21 participant. I would like to work on the **implementation of Stack Class in Python** .
I have read the contribution guidelines as well I request you to kindly assign this issue to me. 

@plazzy99 @nakul-19  @todi-2000 @rudrakshi99

**Comment by Simar05519** [comment] 2021-03-13 15:13
I had an experience as I had worked on projects. I want to work on this issue. Please assign to me.

**Comment by OjusWiZard** [comment] 2021-04-04 08:57
Duplicate of #516

**Closed by OjusWiZard** 2021-04-04 08:57 UTC

**Comment by sujoy-coder** [comment] 2021-04-04 09:38
Thank You for your response 😑
