### ISSUE TITLE
Finding prime number till N by Sieve of Eratosthenes ( Method 2) ( C++)

### ISSUE THREAD

**Issue by rohank2502** [Algo-Phantoms/Algo-Tree#546] opened 2021-03-11 05:37 UTC
In this algorithm i will try to find the number of prime number present till n and give a count with each number !! Will start working on it as soon as i get assigned

**Comment by rudrakshi99** [comment] 2021-03-11 05:44
@rohank2502 Close your previous issues - #478 #479. So that I can assign you these.

**Comment by rohank2502** [comment] 2021-03-11 05:54
Ok i have added one Pr will add second pr In a hour Then I will close both
issues

**Comment by OjusWiZard** [comment] 2021-04-02 19:48
Duplicate of #502

**Closed by OjusWiZard** 2021-04-02 19:48 UTC
