### ISSUE TITLE
Finding Maximum element in Binary Tree

### ISSUE THREAD

**Issue by japneetbhatia** [Algo-Phantoms/Algo-Tree#704] opened 2021-03-11 21:20 UTC
Hello I'm GSSOC'21 participant. I want to work on this isse using java. please assign this to me

**Comment by jeelnathani** [comment] 2021-03-13 04:57
hey, I am GSSOC '21 participant too. I would like to implement it in python

**Comment by shahina-bano** [comment] 2021-03-16 20:22
Please assign this issue, I will solve this using CPP.

**Comment by OjusWiZard** [comment] 2021-04-04 06:31
Duplicate of #703

**Closed by OjusWiZard** 2021-04-04 06:31 UTC
Labels: duplicate
