### ISSUE TITLE
Sparse Matrix C, Java, Python

### ISSUE THREAD

**Issue by Aleena-Ashraf** [Algo-Phantoms/Algo-Tree#465] opened 2021-03-10 15:17 UTC
Hey! I am a GSSoC '21 participant. This is a very potential topic for coding interviews.
So, I would like to implement this in C, Java and Python. Please do assign me this.

**Comment by Aarti002** [comment] 2021-03-10 18:47
hello @rudrakshi99 i'm gssoc'21 participant can i take this issue i will be using c++ for the implementation as we know this is quite important and difficult to understand so i will try my best to explain my code through explanatory comments as well as with some examples.
So, please assign this issue to me 
Thank you!

**Comment by Disha-swp** [comment] 2021-03-11 07:14
hello @rudrakshi99 i'm gssoc'21 participant, i will work on it using c.
So, please assign me this issue
Thank you

**Comment by OjusWiZard** [comment] 2021-04-02 17:58
Duplicate of #333

**Closed by OjusWiZard** 2021-04-02 17:58 UTC
Labels: duplicate
